
version: '3'

services:
  sistemaDB:
    image: postgres:15.3
    container_name: sistema-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./postgres:/var/lib/postgresql/data